name: trunk_ops_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_map: ^7.0.0
  latlong2: ^0.9.0
  http: ^1.2.0

  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.17

  file_picker: ^8.0.0
  file_saver: ^0.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  # пакет для налаштування нативного splash-екрану
  flutter_native_splash: ^2.4.0   # (можеш оновити версію на актуальну при потребі)

flutter:

  uses-material-design: true

  assets:
    - assets/icons/trunkops_logo.svg
    - assets/images/viti_logo.png

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-VariableFont_opsz.ttf
          weight: 100
        - asset: assets/fonts/inter/Inter-VariableFont_opsz.ttf
          weight: 200
        - asset: assets/fonts/inter/Inter-VariableFont_opsz.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter-VariableFont_opsz.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter-VariableFont_opsz.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-VariableFont_opsz.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-VariableFont_opsz.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter-VariableFont_opsz.ttf
          weight: 800
        - asset: assets/fonts/inter/Inter-VariableFont_opsz.ttf
          weight: 900

        - asset: assets/fonts/inter/Inter-Italic-VariableFont_opsz,wght.ttf
          style: italic

    - family: Volja
      fonts:
        - asset: assets/fonts/volja/volja-regular_w.ttf
          weight: 400

# 🔻 конфіг flutter_native_splash (на тому ж рівні, що й `flutter:`)
flutter_native_splash:
  color: "#121613"      # той самий фон, що й у твого екрану
  android: true
  ios: true
  web: false
  android_12:
    color: "#121613"
